<?php

// <editor-fold defaultstate="collapsed" desc="Casa Z">
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/0.jpg', 'src-small' => '/img/Casa Z/0s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/1.jpg', 'src-small' => '/img/Casa Z/1s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/2.jpg', 'src-small' => '/img/Casa Z/2s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/3.jpg', 'src-small' => '/img/Casa Z/3s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/4.jpg', 'src-small' => '/img/Casa Z/4s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/5.jpg', 'src-small' => '/img/Casa Z/5s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/6.jpg', 'src-small' => '/img/Casa Z/6s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/7.jpg', 'src-small' => '/img/Casa Z/7s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/8.jpg', 'src-small' => '/img/Casa Z/8s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/9.jpg', 'src-small' => '/img/Casa Z/9s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/10.jpg', 'src-small' => '/img/Casa Z/10s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/11.jpg', 'src-small' => '/img/Casa Z/11s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/12.jpg', 'src-small' => '/img/Casa Z/12s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/13.jpg', 'src-small' => '/img/Casa Z/13s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/14.jpg', 'src-small' => '/img/Casa Z/14s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/15.jpg', 'src-small' => '/img/Casa Z/15s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/16.jpg', 'src-small' => '/img/Casa Z/16s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/17.jpg', 'src-small' => '/img/Casa Z/17s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/18.jpg', 'src-small' => '/img/Casa Z/18s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/19.jpg', 'src-small' => '/img/Casa Z/19s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/20.jpg', 'src-small' => '/img/Casa Z/20s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/21.jpg', 'src-small' => '/img/Casa Z/21s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/22.jpg', 'src-small' => '/img/Casa Z/22s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/23.jpg', 'src-small' => '/img/Casa Z/23s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/24.jpg', 'src-small' => '/img/Casa Z/24s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/25.jpg', 'src-small' => '/img/Casa Z/25s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/26.jpg', 'src-small' => '/img/Casa Z/26s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/27.jpg', 'src-small' => '/img/Casa Z/27s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/28.jpg', 'src-small' => '/img/Casa Z/28s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/29.jpg', 'src-small' => '/img/Casa Z/29s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/30.jpg', 'src-small' => '/img/Casa Z/30s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/31.jpg', 'src-small' => '/img/Casa Z/31s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/32.jpg', 'src-small' => '/img/Casa Z/32s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/33.jpg', 'src-small' => '/img/Casa Z/33s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/34.jpg', 'src-small' => '/img/Casa Z/34s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/35.jpg', 'src-small' => '/img/Casa Z/35s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/36.jpg', 'src-small' => '/img/Casa Z/36s.jpg', 'title' => 'Título');
$proyects['Casa Z']['img'][] = array('src' => '/img/Casa Z/37.jpg');
$proyects['Casa Z']['title'] = 'Casa Z';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="27 y 71">
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/1.jpg', 'src-small' => '/img/27 y 71/1s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/2.jpg', 'src-small' => '/img/27 y 71/2s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/3.jpg', 'src-small' => '/img/27 y 71/3s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/4.jpg', 'src-small' => '/img/27 y 71/4s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/5.jpg', 'src-small' => '/img/27 y 71/5s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/6.jpg', 'src-small' => '/img/27 y 71/6s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/7.jpg', 'src-small' => '/img/27 y 71/7s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/8.jpg', 'src-small' => '/img/27 y 71/8s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/9.jpg', 'src-small' => '/img/27 y 71/9s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/10.jpg', 'src-small' => '/img/27 y 71/10s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/11.jpg', 'src-small' => '/img/27 y 71/11s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/12.jpg', 'src-small' => '/img/27 y 71/12s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/13.jpg', 'src-small' => '/img/27 y 71/13s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/14.jpg', 'src-small' => '/img/27 y 71/14s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/15.jpg', 'src-small' => '/img/27 y 71/15s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/16.jpg', 'src-small' => '/img/27 y 71/16s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/17.jpg', 'src-small' => '/img/27 y 71/17s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/18.jpg', 'src-small' => '/img/27 y 71/18s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/19.jpg', 'src-small' => '/img/27 y 71/19s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/20.jpg', 'src-small' => '/img/27 y 71/20s.jpg', 'title' => 'Título');
$proyects['27 y 71']['img'][] = array('src' => '/img/27 y 71/21.jpg', 'src-small' => '/img/27 y 71/21s.jpg', 'title' => 'Título');
$proyects['27 y 71']['title'] = '27 y 71';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Bogo">
$proyects['Bogo']['img'][] = array('src' => '/img/Bogo/1.jpg', 'src-small' => '/img/Bogo/1s.jpg', 'title' => 'Título');
$proyects['Bogo']['img'][] = array('src' => '/img/Bogo/2.jpg', 'src-small' => '/img/Bogo/2s.jpg', 'title' => 'Título');
$proyects['Bogo']['title'] = 'Bogo';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Casa Ale-Ale">
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/1.jpg', 'src-small' => '/img/Casa Ale-Ale/1s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/2.jpg', 'src-small' => '/img/Casa Ale-Ale/2s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/3.jpg', 'src-small' => '/img/Casa Ale-Ale/3s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/4.jpg', 'src-small' => '/img/Casa Ale-Ale/4s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/5.jpg', 'src-small' => '/img/Casa Ale-Ale/5s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/6.jpg', 'src-small' => '/img/Casa Ale-Ale/6s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/7.jpg', 'src-small' => '/img/Casa Ale-Ale/7s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/8.jpg', 'src-small' => '/img/Casa Ale-Ale/8s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/9.jpg', 'src-small' => '/img/Casa Ale-Ale/9s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/10.jpg', 'src-small' => '/img/Casa Ale-Ale/10s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['img'][] = array('src' => '/img/Casa Ale-Ale/11.jpg', 'src-small' => '/img/Casa Ale-Ale/11s.jpg', 'title' => 'Título');
$proyects['Casa Ale-Ale']['title'] = 'Casa Ale - Ale';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Casa M">
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/1.jpg', 'src-small' => '/img/Casa M/1s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/2.jpg', 'src-small' => '/img/Casa M/2s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/3.jpg', 'src-small' => '/img/Casa M/3s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/4.jpg', 'src-small' => '/img/Casa M/4s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/5.jpg', 'src-small' => '/img/Casa M/5s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/6.jpg', 'src-small' => '/img/Casa M/6s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/7.jpg', 'src-small' => '/img/Casa M/7s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/8.jpg', 'src-small' => '/img/Casa M/8s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/9.jpg', 'src-small' => '/img/Casa M/9s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/10.jpg', 'src-small' => '/img/Casa M/10s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/11.jpg', 'src-small' => '/img/Casa M/11s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/12.jpg', 'src-small' => '/img/Casa M/12s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/13.jpg', 'src-small' => '/img/Casa M/13s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/14.jpg', 'src-small' => '/img/Casa M/14s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/15.jpg', 'src-small' => '/img/Casa M/15s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/16.jpg', 'src-small' => '/img/Casa M/16s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/17.jpg', 'src-small' => '/img/Casa M/17s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/18.jpg', 'src-small' => '/img/Casa M/18s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/19.jpg', 'src-small' => '/img/Casa M/19s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/20.jpg', 'src-small' => '/img/Casa M/20s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/21.jpg', 'src-small' => '/img/Casa M/21s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/22.jpg', 'src-small' => '/img/Casa M/22s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/23.jpg', 'src-small' => '/img/Casa M/23s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/24.jpg', 'src-small' => '/img/Casa M/24s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/25.jpg', 'src-small' => '/img/Casa M/25s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/26.jpg', 'src-small' => '/img/Casa M/26s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/27.jpg', 'src-small' => '/img/Casa M/27s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/28.jpg', 'src-small' => '/img/Casa M/28s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/29.jpg', 'src-small' => '/img/Casa M/29s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/30.jpg', 'src-small' => '/img/Casa M/30s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/31.jpg', 'src-small' => '/img/Casa M/31s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/32.jpg', 'src-small' => '/img/Casa M/32s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/33.jpg', 'src-small' => '/img/Casa M/33s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/34.jpg', 'src-small' => '/img/Casa M/34s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/35.jpg', 'src-small' => '/img/Casa M/35s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/36.jpg', 'src-small' => '/img/Casa M/36s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/37.jpg', 'src-small' => '/img/Casa M/37s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/38.jpg', 'src-small' => '/img/Casa M/38s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/39.jpg', 'src-small' => '/img/Casa M/39s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/40.jpg', 'src-small' => '/img/Casa M/40s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/41.jpg', 'src-small' => '/img/Casa M/41s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/42.jpg', 'src-small' => '/img/Casa M/42s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/43.jpg', 'src-small' => '/img/Casa M/43s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/44.jpg', 'src-small' => '/img/Casa M/44s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/45.jpg', 'src-small' => '/img/Casa M/45s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/46.jpg', 'src-small' => '/img/Casa M/46s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/47.jpg', 'src-small' => '/img/Casa M/47.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/48.jpg', 'src-small' => '/img/Casa M/48s.jpg', 'title' => 'Título');
$proyects['Casa M']['img'][] = array('src' => '/img/Casa M/49.jpg', 'src-small' => '/img/Casa M/49s.jpg', 'title' => 'Título');
$proyects['Casa M']['title'] = 'Casa M';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="edificio esquina">
$proyects['edificio de esquina']['img'][] = array('src' => '/img/edificio de esquina/1.jpg', 'src-small' => '/img/edificio de esquina/1s.jpg', 'title' => 'Título');
$proyects['edificio de esquina']['img'][] = array('src' => '/img/edificio de esquina/2.jpg', 'src-small' => '/img/edificio de esquina/2s.jpg', 'title' => 'Título');
$proyects['edificio de esquina']['img'][] = array('src' => '/img/edificio de esquina/3.jpg', 'src-small' => '/img/edificio de esquina/3s.jpg', 'title' => 'Título');
$proyects['edificio de esquina']['img'][] = array('src' => '/img/edificio de esquina/4.jpg', 'src-small' => '/img/edificio de esquina/4s.jpg', 'title' => 'Título');
$proyects['edificio de esquina']['img'][] = array('src' => '/img/edificio de esquina/5.jpg', 'src-small' => '/img/edificio de esquina/5s.jpg', 'title' => 'Título');
$proyects['edificio de esquina']['img'][] = array('src' => '/img/edificio de esquina/6.jpg', 'src-small' => '/img/edificio de esquina/6s.jpg', 'title' => 'Título');
$proyects['edificio de esquina']['img'][] = array('src' => '/img/edificio de esquina/7.jpg', 'src-small' => '/img/edificio de esquina/7s.jpg', 'title' => 'Título');
$proyects['edificio de esquina']['title'] = 'edificio de esquina';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Estación Norte">
$proyects['Estacion norte']['img'][] = array('src' => '/img/Estacion norte/1.jpg', 'src-small' => '/img/Estacion norte/1s.jpg', 'title' => 'Título');
$proyects['Estacion norte']['img'][] = array('src' => '/img/Estacion norte/2.jpg', 'src-small' => '/img/Estacion norte/2s.jpg', 'title' => 'Título');
$proyects['Estacion norte']['img'][] = array('src' => '/img/Estacion norte/3.jpg', 'src-small' => '/img/Estacion norte/3s.jpg', 'title' => 'Título');
$proyects['Estacion norte']['img'][] = array('src' => '/img/Estacion norte/4.jpg', 'src-small' => '/img/Estacion norte/4s.jpg', 'title' => 'Título');
$proyects['Estacion norte']['img'][] = array('src' => '/img/Estacion norte/5.jpg', 'src-small' => '/img/Estacion norte/5s.jpg', 'title' => 'Título');
$proyects['Estacion norte']['img'][] = array('src' => '/img/Estacion norte/6.jpg', 'src-small' => '/img/Estacion norte/6s.jpg', 'title' => 'Título');
$proyects['Estacion norte']['img'][] = array('src' => '/img/Estacion norte/7.jpg', 'src-small' => '/img/Estacion norte/7s.jpg', 'title' => 'Título');
$proyects['Estacion norte']['title'] = 'Estacion norte';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="estudio">
$proyects['estudio']['img'][] = array('src' => '/img/estudio/1.jpg', 'src-small' => '/img/estudio/1s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/2.jpg', 'src-small' => '/img/estudio/2s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/3.jpg', 'src-small' => '/img/estudio/3s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/4.jpg', 'src-small' => '/img/estudio/4s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/5.jpg', 'src-small' => '/img/estudio/5s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/6.jpg', 'src-small' => '/img/estudio/6s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/7.jpg', 'src-small' => '/img/estudio/7s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/8.jpg', 'src-small' => '/img/estudio/8s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/9.jpg', 'src-small' => '/img/estudio/9s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/10.jpg', 'src-small' => '/img/estudio/10s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/11.jpg', 'src-small' => '/img/estudio/11s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/12.jpg', 'src-small' => '/img/estudio/12s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/13.jpg', 'src-small' => '/img/estudio/13s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/14.jpg', 'src-small' => '/img/estudio/14s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/15.jpg', 'src-small' => '/img/estudio/15s.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/16.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/17.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/18.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/19.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/20.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/21.jpg', 'title' => 'Título');
$proyects['estudio']['img'][] = array('src' => '/img/estudio/22.jpg', 'title' => 'Título');
$proyects['estudio']['title'] = 'Estudio';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="garage mingo">
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/1.jpg', 'src-small' => '/img/garage mingo/1s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/2.jpg', 'src-small' => '/img/garage mingo/2s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/3.jpg', 'src-small' => '/img/garage mingo/3s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/4.jpg', 'src-small' => '/img/garage mingo/4s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/5.jpg', 'src-small' => '/img/garage mingo/5s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/6.jpg', 'src-small' => '/img/garage mingo/6s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/7.jpg', 'src-small' => '/img/garage mingo/7s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/8.jpg', 'src-small' => '/img/garage mingo/8s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/9.jpg', 'src-small' => '/img/garage mingo/9s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/10.jpg', 'src-small' => '/img/garage mingo/10s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/11.jpg', 'src-small' => '/img/garage mingo/11s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/12.jpg', 'src-small' => '/img/garage mingo/12s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/13.jpg', 'src-small' => '/img/garage mingo/13s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/14.jpg', 'src-small' => '/img/garage mingo/14s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/15.jpg', 'src-small' => '/img/garage mingo/15s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/16.jpg', 'src-small' => '/img/garage mingo/16s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/17.jpg', 'src-small' => '/img/garage mingo/17s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/18.jpg', 'src-small' => '/img/garage mingo/18s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/19.jpg', 'src-small' => '/img/garage mingo/19s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/20.jpg', 'src-small' => '/img/garage mingo/20s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/21.jpg', 'src-small' => '/img/garage mingo/21s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/22.jpg', 'src-small' => '/img/garage mingo/22s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/23.jpg', 'src-small' => '/img/garage mingo/23s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/24.jpg', 'src-small' => '/img/garage mingo/24s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/25.jpg', 'src-small' => '/img/garage mingo/25s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/26.jpg', 'src-small' => '/img/garage mingo/26s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/27.jpg', 'src-small' => '/img/garage mingo/27s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/28.jpg', 'src-small' => '/img/garage mingo/28s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/29.jpg', 'src-small' => '/img/garage mingo/29s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/30.jpg', 'src-small' => '/img/garage mingo/30s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/31.jpg', 'src-small' => '/img/garage mingo/31s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/32.jpg', 'src-small' => '/img/garage mingo/32s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/33.jpg', 'src-small' => '/img/garage mingo/33s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/34.jpg', 'src-small' => '/img/garage mingo/34s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/35.jpg', 'src-small' => '/img/garage mingo/35s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/36.jpg', 'src-small' => '/img/garage mingo/36s.jpg', 'title' => 'Título');
$proyects['garage mingo']['img'][] = array('src' => '/img/garage mingo/37.jpg', 'src-small' => '/img/garage mingo/37s.jpg', 'title' => 'Título');
$proyects['garage mingo']['title'] = 'Garage mingo';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="gisela-pablo">
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/1.jpg', 'src-small' => '/img/gisela-pablo/1s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/2.jpg', 'src-small' => '/img/gisela-pablo/2s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/3.jpg', 'src-small' => '/img/gisela-pablo/3s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/4.jpg', 'src-small' => '/img/gisela-pablo/4s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/5.jpg', 'src-small' => '/img/gisela-pablo/5s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/6.jpg', 'src-small' => '/img/gisela-pablo/6s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/7.jpg', 'src-small' => '/img/gisela-pablo/7s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/8.jpg', 'src-small' => '/img/gisela-pablo/8s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/9.jpg', 'src-small' => '/img/gisela-pablo/9s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/10.jpg', 'src-small' => '/img/gisela-pablo/10s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['img'][] = array('src' => '/img/gisela-pablo/11.jpg', 'src-small' => '/img/gisela-pablo/11s.jpg', 'title' => 'Título');
$proyects['gisela-pablo']['title'] = 'Gisela-Pablo';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Hotel Caviahue">
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/1.jpg', 'src-small' => '/img/Hotel Caviahue/1s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/2.jpg', 'src-small' => '/img/Hotel Caviahue/2s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/3.jpg', 'src-small' => '/img/Hotel Caviahue/3s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/4.jpg', 'src-small' => '/img/Hotel Caviahue/4s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/5.jpg', 'src-small' => '/img/Hotel Caviahue/5s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/6.jpg', 'src-small' => '/img/Hotel Caviahue/6s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/7.jpg', 'src-small' => '/img/Hotel Caviahue/7s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/8.jpg', 'src-small' => '/img/Hotel Caviahue/8s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/9.jpg', 'src-small' => '/img/Hotel Caviahue/9s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/10.jpg', 'src-small' => '/img/Hotel Caviahue/10s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/11.jpg', 'src-small' => '/img/Hotel Caviahue/11s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/12.jpg', 'src-small' => '/img/Hotel Caviahue/12s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/13.jpg', 'src-small' => '/img/Hotel Caviahue/13s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/14.jpg', 'src-small' => '/img/Hotel Caviahue/14s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/16.jpg', 'src-small' => '/img/Hotel Caviahue/16s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/15.jpg', 'src-small' => '/img/Hotel Caviahue/15s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/17.jpg', 'src-small' => '/img/Hotel Caviahue/17s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/18.jpg', 'src-small' => '/img/Hotel Caviahue/18s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/19.jpg', 'src-small' => '/img/Hotel Caviahue/19s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/20.jpg', 'src-small' => '/img/Hotel Caviahue/20s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/21.jpg', 'src-small' => '/img/Hotel Caviahue/21s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/22.jpg', 'src-small' => '/img/Hotel Caviahue/22s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/23.jpg', 'src-small' => '/img/Hotel Caviahue/23s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/24.jpg', 'src-small' => '/img/Hotel Caviahue/24s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/25.jpg', 'src-small' => '/img/Hotel Caviahue/25s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/26.jpg', 'src-small' => '/img/Hotel Caviahue/26s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/27.jpg', 'src-small' => '/img/Hotel Caviahue/27s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/28.jpg', 'src-small' => '/img/Hotel Caviahue/28s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/29.jpg', 'src-small' => '/img/Hotel Caviahue/29s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/30.jpg', 'src-small' => '/img/Hotel Caviahue/30s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/31.jpg', 'src-small' => '/img/Hotel Caviahue/31s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/32.jpg', 'src-small' => '/img/Hotel Caviahue/32s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/33.jpg', 'src-small' => '/img/Hotel Caviahue/33s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/34.jpg', 'src-small' => '/img/Hotel Caviahue/34s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/35.jpg', 'src-small' => '/img/Hotel Caviahue/35s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/36.jpg', 'src-small' => '/img/Hotel Caviahue/36s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/37.jpg', 'src-small' => '/img/Hotel Caviahue/37s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/38.jpg', 'src-small' => '/img/Hotel Caviahue/38s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/39.jpg', 'src-small' => '/img/Hotel Caviahue/39s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/40.jpg', 'src-small' => '/img/Hotel Caviahue/40s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/41.jpg', 'src-small' => '/img/Hotel Caviahue/41s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/42.jpg', 'src-small' => '/img/Hotel Caviahue/42s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/43.jpg', 'src-small' => '/img/Hotel Caviahue/43s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/44.jpg', 'src-small' => '/img/Hotel Caviahue/44s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/45.jpg', 'src-small' => '/img/Hotel Caviahue/45s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/46.jpg', 'src-small' => '/img/Hotel Caviahue/46s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/47.jpg', 'src-small' => '/img/Hotel Caviahue/47s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/48.jpg', 'src-small' => '/img/Hotel Caviahue/48s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/49.jpg', 'src-small' => '/img/Hotel Caviahue/49s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/50.jpg', 'src-small' => '/img/Hotel Caviahue/50s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/51.jpg', 'src-small' => '/img/Hotel Caviahue/51s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/52.jpg', 'src-small' => '/img/Hotel Caviahue/52s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/53.jpg', 'src-small' => '/img/Hotel Caviahue/30s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/54.jpg', 'src-small' => '/img/Hotel Caviahue/31s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/55.jpg', 'src-small' => '/img/Hotel Caviahue/32s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/56.jpg', 'src-small' => '/img/Hotel Caviahue/33s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/57.jpg', 'src-small' => '/img/Hotel Caviahue/34s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/58.jpg', 'src-small' => '/img/Hotel Caviahue/35s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/59.jpg', 'src-small' => '/img/Hotel Caviahue/36s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/60.jpg', 'src-small' => '/img/Hotel Caviahue/37s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/61.jpg', 'src-small' => '/img/Hotel Caviahue/38s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/62.jpg', 'src-small' => '/img/Hotel Caviahue/39s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/63.jpg', 'src-small' => '/img/Hotel Caviahue/40s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/64.jpg', 'src-small' => '/img/Hotel Caviahue/41s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/65.jpg', 'src-small' => '/img/Hotel Caviahue/42s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/66.jpg', 'src-small' => '/img/Hotel Caviahue/43s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/67.jpg', 'src-small' => '/img/Hotel Caviahue/44s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/68.jpg', 'src-small' => '/img/Hotel Caviahue/45s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/69.jpg', 'src-small' => '/img/Hotel Caviahue/46s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/70.jpg', 'src-small' => '/img/Hotel Caviahue/47s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/71.jpg', 'src-small' => '/img/Hotel Caviahue/48s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/72.jpg', 'src-small' => '/img/Hotel Caviahue/49s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/73.jpg', 'src-small' => '/img/Hotel Caviahue/50s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/74.jpg', 'src-small' => '/img/Hotel Caviahue/51s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['img'][] = array('src' => '/img/Hotel Caviahue/75.jpg', 'src-small' => '/img/Hotel Caviahue/52s.jpg', 'title' => 'Título');
$proyects['Hotel Caviahue']['title'] = 'Hotel Caviahue';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="hotel gato negro rosario">
$proyects['hotel gato negro rosario']['img'][] = array('src' => '/img/hotel gato negro rosario/1.jpg', 'src-small' => '/img/hotel gato negro rosario/1s.jpg', 'title' => 'Título');
$proyects['hotel gato negro rosario']['img'][] = array('src' => '/img/hotel gato negro rosario/2.jpg', 'src-small' => '/img/hotel gato negro rosario/2s.jpg', 'title' => 'Título');
$proyects['hotel gato negro rosario']['img'][] = array('src' => '/img/hotel gato negro rosario/3.jpg', 'src-small' => '/img/hotel gato negro rosario/3s.jpg', 'title' => 'Título');
$proyects['hotel gato negro rosario']['img'][] = array('src' => '/img/hotel gato negro rosario/4.jpg', 'src-small' => '/img/hotel gato negro rosario/4s.jpg', 'title' => 'Título');
$proyects['hotel gato negro rosario']['img'][] = array('src' => '/img/hotel gato negro rosario/5.jpg', 'src-small' => '/img/hotel gato negro rosario/5s.jpg', 'title' => 'Título');
$proyects['hotel gato negro rosario']['img'][] = array('src' => '/img/hotel gato negro rosario/6.jpg', 'src-small' => '/img/hotel gato negro rosario/6s.jpg', 'title' => 'Título');
$proyects['hotel gato negro rosario']['img'][] = array('src' => '/img/hotel gato negro rosario/7.jpg', 'src-small' => '/img/hotel gato negro rosario/7s.jpg', 'title' => 'Título');
$proyects['hotel gato negro rosario']['title'] = 'Hotel Gato Negro - Rosario';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Los Fresnos">
$proyects['Los Fresnos']['img'][] = array('src' => '/img/Los Fresnos/1.jpg', 'src-small' => '/img/Los Fresnos/1s.jpg', 'title' => 'Título');
$proyects['Los Fresnos']['img'][] = array('src' => '/img/Los Fresnos/2.jpg', 'src-small' => '/img/Los Fresnos/2s.jpg', 'title' => 'Título');
$proyects['Los Fresnos']['img'][] = array('src' => '/img/Los Fresnos/3.jpg', 'src-small' => '/img/Los Fresnos/3s.jpg', 'title' => 'Título');
$proyects['Los Fresnos']['img'][] = array('src' => '/img/Los Fresnos/4.jpg', 'src-small' => '/img/Los Fresnos/4s.jpg', 'title' => 'Título');
$proyects['Los Fresnos']['img'][] = array('src' => '/img/Los Fresnos/5.jpg', 'src-small' => '/img/Los Fresnos/5s.jpg', 'title' => 'Título');
$proyects['Los Fresnos']['img'][] = array('src' => '/img/Los Fresnos/6.jpg', 'src-small' => '/img/Los Fresnos/6s.jpg', 'title' => 'Título');
$proyects['Los Fresnos']['img'][] = array('src' => '/img/Los Fresnos/7.jpg', 'src-small' => '/img/Los Fresnos/7s.jpg', 'title' => 'Título');
$proyects['Los Fresnos']['img'][] = array('src' => '/img/Los Fresnos/8.jpg', 'src-small' => '/img/Los Fresnos/8s.jpg', 'title' => 'Título');
$proyects['Los Fresnos']['title'] = 'Los Fresnos';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Marisa y Donato">
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/1.jpg', 'src-small' => '/img/Marisa y Donato/1s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/2.jpg', 'src-small' => '/img/Marisa y Donato/2s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/3.jpg', 'src-small' => '/img/Marisa y Donato/3s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/4.jpg', 'src-small' => '/img/Marisa y Donato/4s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/5.jpg', 'src-small' => '/img/Marisa y Donato/5s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/6.jpg', 'src-small' => '/img/Marisa y Donato/6s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/7.jpg', 'src-small' => '/img/Marisa y Donato/7s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/8.jpg', 'src-small' => '/img/Marisa y Donato/8s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/9.jpg', 'src-small' => '/img/Marisa y Donato/9s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/10.jpg', 'src-small' => '/img/Marisa y Donato/10s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/11.jpg', 'src-small' => '/img/Marisa y Donato/11s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/12.jpg', 'src-small' => '/img/Marisa y Donato/12s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/13.jpg', 'src-small' => '/img/Marisa y Donato/13s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/14.jpg', 'src-small' => '/img/Marisa y Donato/14s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['img'][] = array('src' => '/img/Marisa y Donato/15.jpg', 'src-small' => '/img/Marisa y Donato/15s.jpg', 'title' => 'Título');
$proyects['Marisa y Donato']['title'] = 'Marisa y Donato';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Nieves">
$proyects['nieves']['img'][] = array('src' => '/img/nieves/1.jpg', 'src-small' => '/img/nieves/1s.jpg', 'title' => 'Título');
$proyects['nieves']['img'][] = array('src' => '/img/nieves/2.jpg', 'src-small' => '/img/nieves/2s.jpg', 'title' => 'Título');
$proyects['nieves']['img'][] = array('src' => '/img/nieves/3.jpg', 'src-small' => '/img/nieves/3s.jpg', 'title' => 'Título');
$proyects['nieves']['img'][] = array('src' => '/img/nieves/4.jpg', 'src-small' => '/img/nieves/4s.jpg', 'title' => 'Título');
$proyects['nieves']['img'][] = array('src' => '/img/nieves/5.jpg', 'src-small' => '/img/nieves/5s.jpg', 'title' => 'Título');
$proyects['nieves']['img'][] = array('src' => '/img/nieves/6.jpg', 'src-small' => '/img/nieves/6s.jpg', 'title' => 'Título');
$proyects['nieves']['img'][] = array('src' => '/img/nieves/7.jpg', 'src-small' => '/img/nieves/7s.jpg', 'title' => 'Título');
$proyects['nieves']['img'][] = array('src' => '/img/nieves/8.jpg', 'src-small' => '/img/nieves/8s.jpg', 'title' => 'Título');
$proyects['nieves']['img'][] = array('src' => '/img/nieves/9.jpg', 'src-small' => '/img/nieves/9s.jpg', 'title' => 'Título');
$proyects['nieves']['img'][] = array('src' => '/img/nieves/10.jpg', 'src-small' => '/img/nieves/10s.jpg', 'title' => 'Título');
$proyects['nieves']['title'] = 'Nieves';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Rogers Viviana">
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/1.jpg', 'src-small' => '/img/Rogers Viviana/1s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/2.jpg', 'src-small' => '/img/Rogers Viviana/2s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/3.jpg', 'src-small' => '/img/Rogers Viviana/3s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/4.jpg', 'src-small' => '/img/Rogers Viviana/4s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/5.jpg', 'src-small' => '/img/Rogers Viviana/5s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/6.jpg', 'src-small' => '/img/Rogers Viviana/6s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/7.jpg', 'src-small' => '/img/Rogers Viviana/7s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/8.jpg', 'src-small' => '/img/Rogers Viviana/8s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/9.jpg', 'src-small' => '/img/Rogers Viviana/9s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/10.jpg', 'src-small' => '/img/Rogers Viviana/10s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/11.jpg', 'src-small' => '/img/Rogers Viviana/11s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/12.jpg', 'src-small' => '/img/Rogers Viviana/12s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/13.jpg', 'src-small' => '/img/Rogers Viviana/13s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/14.jpg', 'src-small' => '/img/Rogers Viviana/14s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/15.jpg', 'src-small' => '/img/Rogers Viviana/15s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['img'][] = array('src' => '/img/Rogers Viviana/16.jpg', 'src-small' => '/img/Rogers Viviana/16s.jpg', 'title' => 'Título');
$proyects['Rogers Viviana']['title'] = 'Rogers Viviana';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="taller mingo">
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/1.jpg', 'src-small' => '/img/taller mingo/1s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/2.jpg', 'src-small' => '/img/taller mingo/2s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/3.jpg', 'src-small' => '/img/taller mingo/3s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/4.jpg', 'src-small' => '/img/taller mingo/4s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/5.jpg', 'src-small' => '/img/taller mingo/5s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/6.jpg', 'src-small' => '/img/taller mingo/6s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/7.jpg', 'src-small' => '/img/taller mingo/7s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/8.jpg', 'src-small' => '/img/taller mingo/8s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/9.jpg', 'src-small' => '/img/taller mingo/9s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/10.jpg', 'src-small' => '/img/taller mingo/10s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/11.jpg', 'src-small' => '/img/taller mingo/11s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/12.jpg', 'src-small' => '/img/taller mingo/12s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/13.jpg', 'src-small' => '/img/taller mingo/13s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/14.jpg', 'src-small' => '/img/taller mingo/14s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/15.jpg', 'src-small' => '/img/taller mingo/15s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/16.jpg', 'src-small' => '/img/taller mingo/16s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/17.jpg', 'src-small' => '/img/taller mingo/17s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/18.jpg', 'src-small' => '/img/taller mingo/18s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/19.jpg', 'src-small' => '/img/taller mingo/19s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/20.jpg', 'src-small' => '/img/taller mingo/20s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/21.jpg', 'src-small' => '/img/taller mingo/21s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/22.jpg', 'src-small' => '/img/taller mingo/22s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/23.jpg', 'src-small' => '/img/taller mingo/23s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/24.jpg', 'src-small' => '/img/taller mingo/24s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/25.jpg', 'src-small' => '/img/taller mingo/25s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/26.jpg', 'src-small' => '/img/taller mingo/26s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/27.jpg', 'src-small' => '/img/taller mingo/27s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/28.jpg', 'src-small' => '/img/taller mingo/28s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/29.jpg', 'src-small' => '/img/taller mingo/29s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/30.jpg', 'src-small' => '/img/taller mingo/30s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/31.jpg', 'src-small' => '/img/taller mingo/31s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/32.jpg', 'src-small' => '/img/taller mingo/32s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/33.jpg', 'src-small' => '/img/taller mingo/33s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/34.jpg', 'src-small' => '/img/taller mingo/34s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/35.jpg', 'src-small' => '/img/taller mingo/35s.jpg', 'title' => 'Título');
$proyects['taller mingo']['img'][] = array('src' => '/img/taller mingo/36.jpg', 'src-small' => '/img/taller mingo/36s.jpg', 'title' => 'Título');
$proyects['taller mingo']['title'] = 'Taller Mingo';
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="tremowily">
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/1.jpg', 'src-small' => '/img/tremowily/1s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/2.jpg', 'src-small' => '/img/tremowily/2s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/3.jpg', 'src-small' => '/img/tremowily/3s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/4.jpg', 'src-small' => '/img/tremowily/4s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/5.jpg', 'src-small' => '/img/tremowily/5s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/6.jpg', 'src-small' => '/img/tremowily/6s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/7.jpg', 'src-small' => '/img/tremowily/7s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/8.jpg', 'src-small' => '/img/tremowily/8s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/9.jpg', 'src-small' => '/img/tremowily/9s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/10.jpg', 'src-small' => '/img/tremowily/10s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/11.jpg', 'src-small' => '/img/tremowily/11s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/12.jpg', 'src-small' => '/img/tremowily/12s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/13.jpg', 'src-small' => '/img/tremowily/13s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/14.jpg', 'src-small' => '/img/tremowily/14s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/15.jpg', 'src-small' => '/img/tremowily/15s.jpg', 'title' => 'Título');
$proyects['tremowily']['img'][] = array('src' => '/img/tremowily/16.jpg', 'src-small' => '/img/tremowily/16s.jpg', 'title' => 'Título');
$proyects['tremowily']['title'] = 'Tremowily';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Voglino">
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/1.jpg', 'src-small' => '/img/Voglino/1s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/2.jpg', 'src-small' => '/img/Voglino/2s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/3.jpg', 'src-small' => '/img/Voglino/3s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/4.jpg', 'src-small' => '/img/Voglino/4s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/5.jpg', 'src-small' => '/img/Voglino/5s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/6.jpg', 'src-small' => '/img/Voglino/6s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/7.jpg', 'src-small' => '/img/Voglino/7s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/8.jpg', 'src-small' => '/img/Voglino/8s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/9.jpg', 'src-small' => '/img/Voglino/9s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/10.jpg', 'src-small' => '/img/Voglino/10s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/11.jpg', 'src-small' => '/img/Voglino/11s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/12.jpg', 'src-small' => '/img/Voglino/12s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/13.jpg', 'src-small' => '/img/Voglino/13s.jpg', 'title' => 'Título');
$proyects['Voglino']['img'][] = array('src' => '/img/Voglino/14.jpg', 'src-small' => '/img/Voglino/14s.jpg', 'title' => 'Título');
$proyects['Voglino']['title'] = 'Voglino';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Zendri">
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/1.jpg', 'src-small' => '/img/Zendri/1s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/2.jpg', 'src-small' => '/img/Zendri/2s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/3.jpg', 'src-small' => '/img/Zendri/3s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/4.jpg', 'src-small' => '/img/Zendri/4s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/5.jpg', 'src-small' => '/img/Zendri/5s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/6.jpg', 'src-small' => '/img/Zendri/6s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/7.jpg', 'src-small' => '/img/Zendri/7s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/8.jpg', 'src-small' => '/img/Zendri/8s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/9.jpg', 'src-small' => '/img/Zendri/9s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/10.jpg', 'src-small' => '/img/Zendri/10s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/11.jpg', 'src-small' => '/img/Zendri/11s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/12.jpg', 'src-small' => '/img/Zendri/12s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/13.jpg', 'src-small' => '/img/Zendri/13s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/14.jpg', 'src-small' => '/img/Zendri/14s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/15.jpg', 'src-small' => '/img/Zendri/15s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/16.jpg', 'src-small' => '/img/Zendri/16s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/17.jpg', 'src-small' => '/img/Zendri/17s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/18.jpg', 'src-small' => '/img/Zendri/18s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/19.jpg', 'src-small' => '/img/Zendri/19s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/20.jpg', 'src-small' => '/img/Zendri/20s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/21.jpg', 'src-small' => '/img/Zendri/21s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/22.jpg', 'src-small' => '/img/Zendri/22s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/23.jpg', 'src-small' => '/img/Zendri/23s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/24.jpg', 'src-small' => '/img/Zendri/24s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/25.jpg', 'src-small' => '/img/Zendri/25s.jpg', 'title' => 'Título');
$proyects['Zendri']['img'][] = array('src' => '/img/Zendri/26.jpg', 'src-small' => '/img/Zendri/26s.jpg', 'title' => 'Título');
$proyects['Zendri']['Title'] = 'Zendri';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Atlantida">
$proyects['Atlantida']['img'][] = array('src' => '/img/Hotel Los Alamos/atlantida/1.jpg', 'title' => 'Título');
$proyects['Atlantida']['img'][] = array('src' => '/img/Hotel Los Alamos/atlantida/2.jpg', 'title' => 'Título');
$proyects['Atlantida']['img'][] = array('src' => '/img/Hotel Los Alamos/atlantida/3.jpg', 'title' => 'Título');
$proyects['Atlantida']['img'][] = array('src' => '/img/Hotel Los Alamos/atlantida/4.jpg', 'title' => 'Título');
$proyects['Atlantida']['img'][] = array('src' => '/img/Hotel Los Alamos/atlantida/5.jpg', 'title' => 'Título');
$proyects['Atlantida']['img'][] = array('src' => '/img/Hotel Los Alamos/atlantida/6.jpg', 'title' => 'Título');
$proyects['Atlantida']['Title'] = 'Hotel Los Álamos - Atlántida';
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Cupula">
$proyects['Cupula']['img'][] = array('src' => '/img/Hotel Los Alamos/cupula/1.jpg', 'title' => 'Título');
$proyects['Cupula']['img'][] = array('src' => '/img/Hotel Los Alamos/cupula/2.jpg', 'title' => 'Título');
$proyects['Cupula']['img'][] = array('src' => '/img/Hotel Los Alamos/cupula/3.jpg', 'title' => 'Título');
$proyects['Cupula']['Title'] = 'Hotel Los Álamos - Cúpula';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="espejos">
$proyects['Espejos']['img'][] = array('src' => '/img/Hotel Los Alamos/hab espejos/1.jpg', 'title' => 'Título');
$proyects['Espejos']['img'][] = array('src' => '/img/Hotel Los Alamos/hab espejos/2.jpg', 'title' => 'Título');
$proyects['Espejos']['img'][] = array('src' => '/img/Hotel Los Alamos/hab espejos/3.jpg', 'title' => 'Título');
$proyects['Espejos']['Title'] = 'Hotel Los Álamos - Espejos';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Nueva York">
$proyects['NuevaYork']['img'][] = array('src' => '/img/Hotel Los Alamos/hab nueva york/1.jpg', 'title' => 'Título');
$proyects['NuevaYork']['img'][] = array('src' => '/img/Hotel Los Alamos/hab nueva york/2.jpg', 'title' => 'Título');
$proyects['NuevaYork']['img'][] = array('src' => '/img/Hotel Los Alamos/hab nueva york/3.jpg', 'title' => 'Título');
$proyects['NuevaYork']['img'][] = array('src' => '/img/Hotel Los Alamos/hab nueva york/4.jpg', 'title' => 'Título');
$proyects['NuevaYork']['Title'] = 'Hotel Los Álamos - Nueva York';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Piedras">
$proyects['Piedras']['img'][] = array('src' => '/img/Hotel Los Alamos/las piedras/1.jpg', 'title' => 'Título');
$proyects['Piedras']['img'][] = array('src' => '/img/Hotel Los Alamos/las piedras/2.jpg', 'title' => 'Título');
$proyects['Piedras']['img'][] = array('src' => '/img/Hotel Los Alamos/las piedras/3.jpg', 'title' => 'Título');
$proyects['Piedras']['img'][] = array('src' => '/img/Hotel Los Alamos/las piedras/4.jpg', 'title' => 'Título');
$proyects['Piedras']['Title'] = 'Hotel Los Álamos - Las Piedras';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Hotel Extreme">
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/1ra habitacion/1.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/1ra habitacion/2.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/1ra habitacion/3.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/1ra habitacion/4.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/1ra habitacion/5.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/1ra habitacion/6.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/1ra habitacion/7.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/1ra habitacion/8.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/1ra habitacion/9.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/2da habitacion/1.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/2da habitacion/2.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/2da habitacion/3.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/2da habitacion/4.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/2da habitacion/5.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/2da habitacion/6.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/2da habitacion/7.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/2da habitacion/8.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/2da habitacion/9.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/2da habitacion/10.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/3ra habitacion/1.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/3ra habitacion/2.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/3ra habitacion/3.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/3ra habitacion/4.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/3ra habitacion/5.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/3ra habitacion/6.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['img'][] = array('src' => '/img/Hotel Extreme/3ra habitacion/7.jpg', 'title' => 'Título');
$proyects['HotelExtreme']['Title'] = 'Hotel Extreme';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Hotel Park Habitaciones">
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/1/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/1/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/1/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/1/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/1/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/1/6.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/2/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/2/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/2/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/2/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/2/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/2/6.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/3/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/3/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/3/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/3/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/3/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/4/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/4/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/4/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/4/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/4/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/5/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/5/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/5/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/5/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/5/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/5/6.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/5/7.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/5/8.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/5/9.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/5/10.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/6.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/7.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/8.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/9.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/10.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/11.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/6/12.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/7/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/7/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/7/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/7/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/7/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/7/6.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/8/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/8/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/8/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/8/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/8/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/9/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/9/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/10/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/10/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/10/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/10/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/10/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/11/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/11/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/11/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/11/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/11/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/11/6.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/11/7.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/12/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/12/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/13/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/13/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/13/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/13/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/13/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/13/6.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/1.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/2.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/3.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/6.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/4.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/5.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/6.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/7.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/8.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['img'][] = array('src' => '/img/Hotel Park/habitaciones/14/9.jpg', 'title' => 'Título');
$proyects['HotelParkHabitaciones']['Title'] = 'Hotel Park - Habitaciones';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Hotel Park Exterior">
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/1.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/2.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/3.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/4.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/5.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/6.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/7.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/8.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/9.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/10.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/11.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/12.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/13.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/14.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/15.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/16.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/17.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/18.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/19.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/20.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/21.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/22.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/23.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/24.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/25.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/26.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/27.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/28.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/29.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/30.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/31.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/32.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/33.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/34.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/35.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/36.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/37.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/38.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/39.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/40.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/final/41.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/proceso/1.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/proceso/2.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/proceso/3.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/proceso/4.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['img'][] = array('src' => '/img/Hotel Park/exterior/proceso/5.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['Title'] = 'Hotel Park - Exterior';
//</editor-fold>
// <editor-fold defaultstate="collapsed" desc="Hidromasash">
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/1.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/2.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/3.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/4.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/5.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/6.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/7.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/8.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/9.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/10.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/11.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/12.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/13.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/14.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/15.jpg', 'title' => 'Título');
$proyects['Hidromasash']['img'][] = array('src' => '/img/Hidromasash/16.jpg', 'title' => 'Título');
$proyects['HotelParkExterior']['Title'] = 'Hidromasash';
//</editor-fold>
//Barra Z
$proyects['Barra Z']['img'][] = array('src' => '/img/Barra Z/1.jpg', 'title' => 'Título');
$proyects['Barra Z']['img'][] = array('src' => '/img/Barra Z/2.jpg', 'title' => 'Título');
$proyects['Barra Z']['img'][] = array('src' => '/img/Barra Z/3.jpg', 'title' => 'Título');
$proyects['Barra Z']['img'][] = array('src' => '/img/Barra Z/4.jpg', 'title' => 'Título');
$proyects['Barra Z']['img'][] = array('src' => '/img/Barra Z/5.jpg', 'title' => 'Título');
$proyects['Barra Z']['img'][] = array('src' => '/img/Barra Z/6.jpg', 'title' => 'Título');
$proyects['Barra Z']['img'][] = array('src' => '/img/Barra Z/7.jpg', 'title' => 'Título');
$proyects['Barra Z']['img'][] = array('src' => '/img/Barra Z/8.jpg', 'title' => 'Título');
$proyects['Barra Z']['img'][] = array('src' => '/img/Barra Z/9.jpg', 'title' => 'Título');

//Reforma Carowilly
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/1.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/2.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/3.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/5.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/6.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/8.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/10.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/11.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/12.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/13.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/14.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/16.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/17.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/19.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/20.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/22.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/23.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/24.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/25.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/26.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/27.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/30.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/32.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/33.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/34.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/35.jpg', 'title' => 'Título');
$proyects['Reforma Carowilly']['img'][] = array('src' => '/img/Reforma carowilly/36.jpg', 'title' => 'Título');


